
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: 'MACFOS OFFICIAL'
logo: "https://i.postimg.cc/RZGpyyJq/Group-4.png"
logo_dark: "https://i.postimg.cc/5Nch6fyb/avatar-dark.png"
email: your-email@domain.com
author: Rajan Yadav
site_url: macfoslab.in
copyright: Copyright © 
description: >- # this means to ignore newlines until "baseurl:"
  Official website of MACFOS Lab, Army Institute of Technology.

baseurl: "/macfos" 
url: "https://hatchedland.github.io/macfos/"
favicon: "" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %d, %Y"
# debug: false
header_transparent: false

# Google analytics
# google_analytics: [Tracking ID]

sitemap: true
lang: "en" 

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    text: English

  - lang: hi
    text: Hindi

  - lang: mr
    text: Marathi


# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrfey: #353535
# snowwhite: #fffff
#
theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"
 
# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "off"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
   - index.html
   - projects.html
   - equipments.html
   - blogs.html
   - tags.html
  

  # vanta
vanta: true       # Enable vanta background 
vanta-theme: net       # options: globe, net, dots, wave


# Disqus comments
disqus:
  shortname: "hatchedland"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

collections:
      equipments:
        output: true
      projects:
        output: true


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
